package com.sztech.cleangovern.model.entity;


import java.io.Serializable;

public class FeebackProblemInterfaceDO implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback_problem_interface.ID
     *
     * @mbggenerated Tue Sep 25 10:17:34 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback_problem_interface.PROBLEM_ID
     *
     * @mbggenerated Tue Sep 25 10:17:34 CST 2018
     */
    private Integer problemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback_problem_interface.INTERFACE_CODE
     *
     * @mbggenerated Tue Sep 25 10:17:34 CST 2018
     */
    private String interfaceCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback_problem_interface.INTERFACE_NAME
     *
     * @mbggenerated Tue Sep 25 10:17:34 CST 2018
     */
    private String interfaceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback_problem_interface.DATA_NUM
     *
     * @mbggenerated Tue Sep 25 10:17:34 CST 2018
     */
    private Integer dataNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback_problem_interface.INTERFACE_PARAM
     *
     * @mbggenerated Tue Sep 25 10:17:34 CST 2018
     */
    private String interfaceParam;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback_problem_interface.PARAM_VALUE
     *
     * @mbggenerated Tue Sep 25 10:17:34 CST 2018
     */
    private String paramValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback_problem_interface.TABLE_NAME
     *
     * @mbggenerated Tue Sep 25 10:17:34 CST 2018
     */
    private String tableName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback_problem_interface.TABLE_COLUMN_NAME
     *
     * @mbggenerated Tue Sep 25 10:17:34 CST 2018
     */
    private String tableColumnName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback_problem_interface.INTERFACE_PARAM_TYPE
     *
     * @mbggenerated Tue Sep 25 10:17:34 CST 2018
     */
    private String interfaceParamType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback_problem_interface.PROBLEM_DESC
     *
     * @mbggenerated Tue Sep 25 10:17:34 CST 2018
     */
    private String problemDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback_problem_interface.ID
     *
     * @return the value of feedback_problem_interface.ID
     *
     * @mbggenerated Tue Sep 25 10:17:34 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback_problem_interface.ID
     *
     * @param id the value for feedback_problem_interface.ID
     *
     * @mbggenerated Tue Sep 25 10:17:34 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback_problem_interface.PROBLEM_ID
     *
     * @return the value of feedback_problem_interface.PROBLEM_ID
     *
     * @mbggenerated Tue Sep 25 10:17:34 CST 2018
     */
    public Integer getProblemId() {
        return problemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback_problem_interface.PROBLEM_ID
     *
     * @param problemId the value for feedback_problem_interface.PROBLEM_ID
     *
     * @mbggenerated Tue Sep 25 10:17:34 CST 2018
     */
    public void setProblemId(Integer problemId) {
        this.problemId = problemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback_problem_interface.INTERFACE_CODE
     *
     * @return the value of feedback_problem_interface.INTERFACE_CODE
     *
     * @mbggenerated Tue Sep 25 10:17:34 CST 2018
     */
    public String getInterfaceCode() {
        return interfaceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback_problem_interface.INTERFACE_CODE
     *
     * @param interfaceCode the value for feedback_problem_interface.INTERFACE_CODE
     *
     * @mbggenerated Tue Sep 25 10:17:34 CST 2018
     */
    public void setInterfaceCode(String interfaceCode) {
        this.interfaceCode = interfaceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback_problem_interface.INTERFACE_NAME
     *
     * @return the value of feedback_problem_interface.INTERFACE_NAME
     *
     * @mbggenerated Tue Sep 25 10:17:34 CST 2018
     */
    public String getInterfaceName() {
        return interfaceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback_problem_interface.INTERFACE_NAME
     *
     * @param interfaceName the value for feedback_problem_interface.INTERFACE_NAME
     *
     * @mbggenerated Tue Sep 25 10:17:34 CST 2018
     */
    public void setInterfaceName(String interfaceName) {
        this.interfaceName = interfaceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback_problem_interface.DATA_NUM
     *
     * @return the value of feedback_problem_interface.DATA_NUM
     *
     * @mbggenerated Tue Sep 25 10:17:34 CST 2018
     */
    public Integer getDataNum() {
        return dataNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback_problem_interface.DATA_NUM
     *
     * @param dataNum the value for feedback_problem_interface.DATA_NUM
     *
     * @mbggenerated Tue Sep 25 10:17:34 CST 2018
     */
    public void setDataNum(Integer dataNum) {
        this.dataNum = dataNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback_problem_interface.INTERFACE_PARAM
     *
     * @return the value of feedback_problem_interface.INTERFACE_PARAM
     *
     * @mbggenerated Tue Sep 25 10:17:34 CST 2018
     */
    public String getInterfaceParam() {
        return interfaceParam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback_problem_interface.INTERFACE_PARAM
     *
     * @param interfaceParam the value for feedback_problem_interface.INTERFACE_PARAM
     *
     * @mbggenerated Tue Sep 25 10:17:34 CST 2018
     */
    public void setInterfaceParam(String interfaceParam) {
        this.interfaceParam = interfaceParam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback_problem_interface.PARAM_VALUE
     *
     * @return the value of feedback_problem_interface.PARAM_VALUE
     *
     * @mbggenerated Tue Sep 25 10:17:34 CST 2018
     */
    public String getParamValue() {
        return paramValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback_problem_interface.PARAM_VALUE
     *
     * @param paramValue the value for feedback_problem_interface.PARAM_VALUE
     *
     * @mbggenerated Tue Sep 25 10:17:34 CST 2018
     */
    public void setParamValue(String paramValue) {
        this.paramValue = paramValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback_problem_interface.TABLE_NAME
     *
     * @return the value of feedback_problem_interface.TABLE_NAME
     *
     * @mbggenerated Tue Sep 25 10:17:34 CST 2018
     */
    public String getTableName() {
        return tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback_problem_interface.TABLE_NAME
     *
     * @param tableName the value for feedback_problem_interface.TABLE_NAME
     *
     * @mbggenerated Tue Sep 25 10:17:34 CST 2018
     */
    public void setTableName(String tableName) {
        this.tableName = tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback_problem_interface.TABLE_COLUMN_NAME
     *
     * @return the value of feedback_problem_interface.TABLE_COLUMN_NAME
     *
     * @mbggenerated Tue Sep 25 10:17:34 CST 2018
     */
    public String getTableColumnName() {
        return tableColumnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback_problem_interface.TABLE_COLUMN_NAME
     *
     * @param tableColumnName the value for feedback_problem_interface.TABLE_COLUMN_NAME
     *
     * @mbggenerated Tue Sep 25 10:17:34 CST 2018
     */
    public void setTableColumnName(String tableColumnName) {
        this.tableColumnName = tableColumnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback_problem_interface.INTERFACE_PARAM_TYPE
     *
     * @return the value of feedback_problem_interface.INTERFACE_PARAM_TYPE
     *
     * @mbggenerated Tue Sep 25 10:17:34 CST 2018
     */
    public String getInterfaceParamType() {
        return interfaceParamType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback_problem_interface.INTERFACE_PARAM_TYPE
     *
     * @param interfaceParamType the value for feedback_problem_interface.INTERFACE_PARAM_TYPE
     *
     * @mbggenerated Tue Sep 25 10:17:34 CST 2018
     */
    public void setInterfaceParamType(String interfaceParamType) {
        this.interfaceParamType = interfaceParamType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback_problem_interface.PROBLEM_DESC
     *
     * @return the value of feedback_problem_interface.PROBLEM_DESC
     *
     * @mbggenerated Tue Sep 25 10:17:34 CST 2018
     */
    public String getProblemDesc() {
        return problemDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback_problem_interface.PROBLEM_DESC
     *
     * @param problemDesc the value for feedback_problem_interface.PROBLEM_DESC
     *
     * @mbggenerated Tue Sep 25 10:17:34 CST 2018
     */
    public void setProblemDesc(String problemDesc) {
        this.problemDesc = problemDesc;
    }
}